// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/verystar/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func inject(s string) Pair {
	message := NewMessage(s)
	mainMessage := NewMessage2(s)
	pair := NewPair(message, mainMessage)
	return pair
}
